In [1]:
import numpy as np
np.__version__

'1.19.2'

In [2]:
arr = np.zeros(4 * 4)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
arr[0] = 1
arr[1] = 2
arr[2] = 3
np.random.shuffle(arr)
arr

array([2., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 3., 0., 0., 0.])

In [6]:
arr.resize((4,4))
arr

array([[2., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [3., 0., 0., 0.]])

In [7]:
arr

array([[2., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [3., 0., 0., 0.]])