In [1]:
import numpy as np
np.__version__

'1.19.2'

In [2]:
arr = np.zeros(4 * 4)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
arr[0] = 1
arr[1] = 2
arr[2] = 3
np.random.shuffle(arr)
arr

array([2., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 3., 0., 0., 0.])

In [4]:
arr.resize((4,4))
arr

array([[2., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [3., 0., 0., 0.]])

In [9]:
data = np.ones( 4 * 4 -3 )
data = np.insert(data, 0, 0) 
data = np.insert(data, 1, 0)
data = np.insert(data, 4, 0)  
data.resize((4,4))
data

array([[0., 0., 1., 1.],
       [0., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [1]:
import pygame,sys
pygame.init() #初始化pygame模块
screen = pygame.display.set_mode((400,300)) #长400，宽300
font = pygame.font.Font('freesansbold.ttf', 32) # 设置文字，字体为freesansbold，字号为32
surface = font.render('Hello world!', True, (0, 255, 0), (0, 0, 255)) # 根据字体创建文字
rect = surface.get_rect() # 获得文字位置和宽高
  
while True: # 循环渲染
  screen.fill((0, 0, 0)) # 画黑色背景
  if rect.x > 400:
    rect.x = -rect.width # 飞出画面回到原点
  else:
    rect.x += 1 # 文字向右移动
  screen.blit(surface, rect) # 画文字
  for event in pygame.event.get(): # 退出处理
    if event.type == pygame.QUIT:
      pygame.quit()
      sys.exit()
  pygame.display.update() # 更新渲染

ModuleNotFoundError: No module named 'pygame'