In [1]:
import numpy as np
np.__version__

'1.19.2'

In [2]:
arr = np.zeros(4 * 4)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
arr[0] = 1
arr[1] = 2
arr[2] = 3
np.random.shuffle(arr)
arr

array([2., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 3., 0., 0., 0.])

In [4]:
arr.resize((4,4))
arr

array([[2., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [3., 0., 0., 0.]])

In [9]:
data = np.ones( 4 * 4 -3 )
data = np.insert(data, 0, 0) 
data = np.insert(data, 1, 0)
data = np.insert(data, 4, 0)  
data.resize((4,4))
data

array([[0., 0., 1., 1.],
       [0., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
import pygame
pygame.font.get_fonts()

ModuleNotFoundError: No module named 'pygame'

In [8]:
arr[-1][-1]

IndexError: invalid index to scalar variable.